# Generated by Django 4.2.11 on 2024-05-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itinerary',
            new_name='itinerary_master',
        ),
    ]
