# Generated by Django 3.2.25 on 2024-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_rename_itinerary_itinerary_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryMaster',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itinerary_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='itinerary_master',
        ),
    ]
