# Generated by Django 3.2.25 on 2024-05-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_auto_20240504_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('activity', models.CharField(max_length=200)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itinerarymaster')),
            ],
        ),
    ]
