# Generated by Django 4.2.11 on 2024-05-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_itinerarydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarydetails',
            options={'managed': False},
        ),
    ]
