# Generated by Django 4.2.11 on 2024-05-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_alter_itinerarydetails_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itinerarydetails',
            table='itinerarydetails',
        ),
    ]
