# Generated by Django 4.2.11 on 2024-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_alter_itinerarydetails_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryTemp',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=45, null=True)),
                ('quotation_id', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'itinerarytemp',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='itinerarymaster',
            table='itinerarymaster',
        ),
        migrations.DeleteModel(
            name='ItineraryDetails',
        ),
    ]
