# Generated by Django 4.2.11 on 2024-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_itinerarymain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItineraryMain',
        ),
    ]
